### ISSUE TITLE
No easy way to import main function

### ISSUE THREAD

**Issue by adhikasp** [araichev/kml2geojson#2]
Hi,

I found no straight forward way to use the main function of the script (convert kml to geojson) inside a python program, as an imported module. The workaround I use is this (based on [ways to test program on click](http://click.pocoo.org/5/testing/))

```python
import kml2geojson.kml2geojson
from click import CliRunner

runner = CliRunner()
runner.invoke(kml2geojson.kml2geojson.main, ["file.kml", "./"])
```

Trying to use `kml2geojson.main(kml_path="file.kml", output_dir="./")` directly result in error  in `click` module.
```
Traceback (most recent call last):
  File "./script.py", line 41, in <module>
    kml2geojson.kml2geojson.main(kml_path="file.kml", output_dir="./")
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 618, in make_context
    ctx = Context(self, info_name=info_name, parent=parent, **extra)
TypeError: __init__() got an unexpected keyword argument 'output_dir'
```

It would be great if the main function could be used directly on a python script, not just as CLI program.  
If you agree, I could separate the `main()` function with the CLI parser and send PR request. I think it will make the main() possible to be called in other module. 😄

**Comment by araichev** [comment]
Hi adhikasp, i just noticed your issue. 
Sorry for my delayed response.

Yes, good idea to separate that functionality.
I was a Click newbie when i wrote ``kml2geojson``.
Now that i have a little more experience, i think that a clean way to do the separation would be create another module called ``cli.py`` in which a copy of the main function would reside.
I took that approach when i wrote the [Wavetrace package](https://github.com/NZRS/wavetrace).
I'll work on the separation tomorrow.

**Comment by araichev** [comment]
Done. Give version 4.0.0 a whirl.
