### ISSUE TITLE
FeatureCollection 'properties' are not allowed by RFC 7946

### ISSUE THREAD

**Issue by sgillies** [araichev/kml2geojson#5]
Hi, @araichev. This is a great looking project and I can attest that it is getting used! People are uploading GeoJSON created by your kml2geojson to Mapbox (where I work).

RFC 7946, the GeoJSON spec, [does not allow FeatureCollections to have a 'properties' member](https://tools.ietf.org/html/rfc7946#section-7). The motivation: it's easier to develop incremental parsers if FeatureCollections and Features don't share keys. Mapbox uploads are strictly validated against RFC 7946.

Instead of giving FeatureCollections a 'properties' member at https://github.com/araichev/kml2geojson/blob/master/kml2geojson/main.py#L497-L498, I suggest putting 'name' directly under the FeatureCollection.

Thanks for your consideration!

**Comment by araichev** [comment]
Thanks for the compliment and information, sgillies.  
I wrote ``kml2geojson`` for some projects at work and am pleasantly surprised to hear that other people around the world are using it too.
Too bad they're all producing invalid GeoJSON!
I'll incorporate your fix in a new release today.
